name: Simulated Backup and Deploy

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'  # Runs daily at 1 AM UTC

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run backup script
        run: bash backup-simulator/auto_backup.sh

      - name: Upload backup result as artifact
  	uses: actions/upload-artifact@v4
 	with:
    	name: backup-results
    	path: |
      	  backups/
      	  backup_log.txt

      - name: Simulate deploy
        run: |
          mkdir -p deployed_backups
          cp backup-simulator/backups/*.tar.gz deployed_backups/ || echo "No backup files found to deploy."
          cp backup-simulator/backup_log.txt deployed_backups/ || echo "No log file found."
          echo "Backup successfully deployed locally at $(date)" >> deployed_backups/deploy_log.txt
          ls -lh deployed_backups