name: Simulated Backup and Deploy

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  backup_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run backup script
        run: bash backup-simulator/auto_backup.sh

      - name: List files after backup
        run: ls -R

      - name: Upload backup result as artifact
        uses: actions/upload-artifact@v4
        with:
          name: backup-results
          path: |
            backups/
            backup_log.txt

      - name: Simulate deploy
        run: echo "Simulated deploy step completed successfully."